export const projects = [
  {
    id: "cvr",
    title: "Center for Vein Restoration",
    description: "Center for Vein Restoration (CVR) is a national network of vein specialists with a high-traffic website serving about 6,000 daily users. As the lead engineer, I oversee all aspects of development, from implementing and maintaining components to ensuring performance, accessibility, and SEO optimization. I also develop Cypress end-to-end tests to guarantee reliability, reduce technical debt, and improve efficiency. Additionally, I collaborate with the client’s in-house developers, providing guidance on best practices and creating documentation to support onboarding and ongoing initiatives.",
    url: "https://www.centerforvein.com",
    video: {
      webm: "",
      mp4: "assets/video/cvr-flow.mp4",
      poster: "assets/images/cvr-flow.webp",
      width: "1920",
      height: "1080",
    },
    industry: "Healthcare",
    stack: [
      "Craft CMS",
      "PHP/Yii2",
      "TailwindCSS",
      "JavaScript",
      "Cypress",
      "Buddy CI"
    ],
    impact: [
      { title: '103', text: 'Unique components.' },
      { figure: '53%', text: 'Reduction in total JavaScript/CSS bundle size.' },
      { figure: '100', text: 'Accessibility score (sitewide) from Lighthouse.' },
      { figure: '0', text: 'Downtime due to component failure thanks to Cypress E2E testing.' }
    ],
    role: "Lead Engineer",
    color: "#1d4589",
  },
  {
    id: "wallcore",
    title: "Wallcore.com",
    description: "Wallcore is an online picture framing startup that partners with local frame shops. I worked with the partners to design and implement a robust web app with which users were able to mat and frame their images, customize design options, and pickup the completed product from their local framer.",
    // url: "https://www.wallcore.com",
    video: {
      webm: "assets/video/wallcore-design-tool.webm",
      mp4: "assets/video/wallcore-design-tool.mp4",
      poster: "assets/images/wallcore-design-tool.png",
      width: "1440",
      height: "810",
    },
    industry: "Custom Picture Framing",
    stack: [
      "E-Commerce",
      "Craft CMS",
      "Stripe",
      "React",
      "Vue",
    ],
    role: "Lead Engineer / Art Director",
    color: "#0085de",
  },
  {
    id: "transit-center",
    title: "Transit Center",
    description: "Transit Center is a foundation dedicated to urban mobility. They needed a website which would help them communicate with residents and policy makers in urban areas to affect change. We developed a modular system of content with which they can publish online reports about transit use. In addition, the site is also a place to search grant recipients, see upcoming events, and read their blog.",
    // url: 'http://transitcenter.org/',
    video: {
      webm: "assets/video/transit-center-flow.webm",
      mp4: "assets/video/transit-center-flow.mp4",
      poster: "assets/images/transit-center-flow.png",
      width: "1422",
      height: "810",
    },
    industry: "Transportation",
    stack: ["Wordpress", "AJAX", "Fluid UI", "Modular Content"],
    role: "Fullstack Engineer",
    color: "#5E28B2",
  },
  {
    id: "hester-street",
    title: "Hester Street Collaborative",
    description: "Hester Street is an urban planning, design and development nonprofit based in the Lower East Side of Manhattan. After a rebranding process, we built a website which allows them to showcase their impact on the communities they serve.",
    url: "http://hesterstreet.org/",
    video: {
      webm: "assets/video/hester-project-scroll.webm",
      mp4: "assets/video/hester-project-scroll.mp4",
      poster: "assets/images/hester-project-scroll.png",
      width: "1584",
      height: "898",
    },
    industry: "Urban Planning",
    stack: [
      "Wordpress",
      "Mapbox",
      "Vue",
    ],
    role: "Fullstack Engineer",
    color: "#21b07a",
  },
  {
    id: "gibney",
    title: "Gibney",
    description: "Gibney, formerly Gibney Dance, is an organization whose mission is to bring the possibility of movement where it otherwise would not exist. Their new site seeks to emphasize the full scope of Gibney, acting as a portal connecting users to the myriad performances, workshops, and weekly events.",
    // url: 'http://gibneydance.org/',
    video: {
      webm: "assets/video/gibney-flow.webm",
      mp4: "assets/video/gibney-flow.mp4",
      poster: "assets/images/gibney-flow.png",
      width: "1422",
      height: "958",
    },
    industry: "Performing Arts",
    stack: ["Wordpress", "Events Calendar", "slick.js"],
    role: "Fullstack Engineer",
    color: "#000000",
  },
  // {
  //   id: "orpheus",
  //   title: "Orpheus Chamber Orchestra",
  //   description: "Orpheus is a a grammy-winning, conductorless orchestra based in New York City. They needed a website to keep patrons informed about their activities and performances around the world. We created a site which is built on a system of customizable tiles and colors the admins can use to create dynamic pages. It is also a source of information about the group's members, discography, and ticket outlets.",
  //   // url: 'http://orpheusnyc.org/',
  //   video: {
  //     webm: "assets/video/orpheus-flow-1.webm",
  //     mp4: "assets/video/orpheus-flow-1.mp4",
  //     poster: "assets/images/orpheus-flow-1.png",
  //     width: "1678",
  //     height: "942",
  //   },
  //   industry: "Performing Arts",
  //   stack: [
  //     "Wordpress",
  //     "Events Calendar",
  //     "Modular Content",
  //   ],
  //   role: "Fullstack Engineer",
  //   color: "#C48014",
  // },
  // {
  //   id: "cgu",
  //   title: "Claremont Graduate University",
  //   text: 'Claremont Graduate University (CGU) is a research-based graduate institution based in Claremont, CA. After a brand "refresh" and extension, we sought to build a site which could act as a portal for faculty, visitors, and potential and current students. A suite of Wordpress themes was ultimately delivered which CGU could use to build everything from small sub-domain sites to faculty blogs. In addition, we built a brand site which acts as a tool for maintaining visual consistency accross the varied digital and print material developed by CGU staff &rarr; <a href="https://brand.cgu.edu/" target="_blank"><em>brand.cgu.edu</em></a>.',
  //   url: "http://cgu.edu/",
  //   video: {
  //     webm: "assets/video/cgu-flow.webm",
  //     mp4: "assets/video/cgu-flow.mp4",
  //     poster: "assets/images/cgu-flow.png",
  //     width: "1424",
  //     height: "956",
  //   },
  //   industry: "Higher Education",
  //   stack: ["Wordpress", "Modular UI", "AJAX"],
  //   role: "Front-End Engineer",
  //   color: "#AF1E27",
  // }
];
